export const ADD_PROGRAMS = 'ADD_PROGRAMS'

export const AUTHENTICATE_USER = 'AUTHENTICATE_USER'

export const FETCH_PROGRAMS = 'FETCH_PROGRAMS'

export const SET_SELECTED_PROGRAM = 'SET_SELECTED_PROGRAM'